"""Address model created

Revision ID: 2d682c0a2942
Revises: 
Create Date: 2026-05-11 19:00:01.689056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d682c0a2942'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
