"""The type of address id edited

Revision ID: a5db4313c641
Revises: 2d682c0a2942
Create Date: 2026-05-12 10:25:45.851977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5db4313c641'
down_revision: Union[str, Sequence[str], None] = '2d682c0a2942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'id',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
