"""message

Revision ID: ec6e88c83105
Revises: afbf4cfd911f
Create Date: 2026-05-22 23:56:19.743237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6e88c83105'
down_revision: Union[str, Sequence[str], None] = 'afbf4cfd911f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'avatar', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'avatar', type_='unique')
    # ### end Alembic commands ###
