# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x1a\x1bgoogle/protobuf/empty.proto\"l\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0b\n\x03tel\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\x11\n\tis_seller\x18\x05 \x01(\x08\x12\x12\n\nlast_login\x18\x07 \x01(\t\"!\n\x12SendSMSCodeRequest\x12\x0b\n\x03tel\x18\x01 \x01(\t\")\n\x0cLoginRequest\x12\x0b\n\x03tel\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\":\n\x18UpdateAccessTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\"X\n\x10\x41uthInfoResponse\x12\x17\n\x04user\x18\x01 \x01(\x0b\x32\t.UserInfo\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\"*\n\x19UpdateAccessTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t2\xc0\x01\n\x0b\x41uthService\x12:\n\x0bSendSMSCode\x12\x13.SendSMSCodeRequest\x1a\x16.google.protobuf.Empty\x12)\n\x05Login\x12\r.LoginRequest\x1a\x11.AuthInfoResponse\x12J\n\x11UpdateAccessToken\x12\x19.UpdateAccessTokenRequest\x1a\x1a.UpdateAccessTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFO']._serialized_start=43
  _globals['_USERINFO']._serialized_end=151
  _globals['_SENDSMSCODEREQUEST']._serialized_start=153
  _globals['_SENDSMSCODEREQUEST']._serialized_end=186
  _globals['_LOGINREQUEST']._serialized_start=188
  _globals['_LOGINREQUEST']._serialized_end=229
  _globals['_UPDATEACCESSTOKENREQUEST']._serialized_start=231
  _globals['_UPDATEACCESSTOKENREQUEST']._serialized_end=289
  _globals['_AUTHINFORESPONSE']._serialized_start=291
  _globals['_AUTHINFORESPONSE']._serialized_end=379
  _globals['_UPDATEACCESSTOKENRESPONSE']._serialized_start=381
  _globals['_UPDATEACCESSTOKENRESPONSE']._serialized_end=423
  _globals['_AUTHSERVICE']._serialized_start=426
  _globals['_AUTHSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
