# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import seckill_pb2 as seckill__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in seckill_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeckillServiceStub(object):
    """
    Overview: 
    1. GetSeckillDetail: GetSeckillDetailRequest -> GetSeckillDetailResponse
    2. GetSeckillList: GetSeckillListRequest -> GetSeckillListResponse
    3. GetOrderList: GetOrderListRequest -> GetOrderListResponse
    4. CreateOrder: CreateOrderRequest -> CreateOrderResponse
    5. MakePayment: MakePaymentRequest -> MakePaymentResponse
    6. PostPaymentResult: PostPaymentResultRequest -> PostPaymentResultResponse

    Services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeckillDetail = channel.unary_unary(
                '/SeckillService/GetSeckillDetail',
                request_serializer=seckill__pb2.GetSeckillDetailRequest.SerializeToString,
                response_deserializer=seckill__pb2.GetSeckillDetailResponse.FromString,
                _registered_method=True)
        self.GetSeckillList = channel.unary_unary(
                '/SeckillService/GetSeckillList',
                request_serializer=seckill__pb2.GetSeckillListRequest.SerializeToString,
                response_deserializer=seckill__pb2.GetSeckillListResponse.FromString,
                _registered_method=True)
        self.GetOrderList = channel.unary_unary(
                '/SeckillService/GetOrderList',
                request_serializer=seckill__pb2.GetOrderListRequest.SerializeToString,
                response_deserializer=seckill__pb2.GetOrderListResponse.FromString,
                _registered_method=True)
        self.CreateOrder = channel.unary_unary(
                '/SeckillService/CreateOrder',
                request_serializer=seckill__pb2.CreateOrderRequest.SerializeToString,
                response_deserializer=seckill__pb2.CreateOrderResponse.FromString,
                _registered_method=True)
        self.MakePayment = channel.unary_unary(
                '/SeckillService/MakePayment',
                request_serializer=seckill__pb2.MakePaymentRequest.SerializeToString,
                response_deserializer=seckill__pb2.MakePaymentResponse.FromString,
                _registered_method=True)
        self.PostPaymentResult = channel.unary_unary(
                '/SeckillService/PostPaymentResult',
                request_serializer=seckill__pb2.PostPaymentResultRequest.SerializeToString,
                response_deserializer=seckill__pb2.PostPaymentResultResponse.FromString,
                _registered_method=True)


class SeckillServiceServicer(object):
    """
    Overview: 
    1. GetSeckillDetail: GetSeckillDetailRequest -> GetSeckillDetailResponse
    2. GetSeckillList: GetSeckillListRequest -> GetSeckillListResponse
    3. GetOrderList: GetOrderListRequest -> GetOrderListResponse
    4. CreateOrder: CreateOrderRequest -> CreateOrderResponse
    5. MakePayment: MakePaymentRequest -> MakePaymentResponse
    6. PostPaymentResult: PostPaymentResultRequest -> PostPaymentResultResponse

    Services
    """

    def GetSeckillDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeckillList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostPaymentResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeckillServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeckillDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeckillDetail,
                    request_deserializer=seckill__pb2.GetSeckillDetailRequest.FromString,
                    response_serializer=seckill__pb2.GetSeckillDetailResponse.SerializeToString,
            ),
            'GetSeckillList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeckillList,
                    request_deserializer=seckill__pb2.GetSeckillListRequest.FromString,
                    response_serializer=seckill__pb2.GetSeckillListResponse.SerializeToString,
            ),
            'GetOrderList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderList,
                    request_deserializer=seckill__pb2.GetOrderListRequest.FromString,
                    response_serializer=seckill__pb2.GetOrderListResponse.SerializeToString,
            ),
            'CreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrder,
                    request_deserializer=seckill__pb2.CreateOrderRequest.FromString,
                    response_serializer=seckill__pb2.CreateOrderResponse.SerializeToString,
            ),
            'MakePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePayment,
                    request_deserializer=seckill__pb2.MakePaymentRequest.FromString,
                    response_serializer=seckill__pb2.MakePaymentResponse.SerializeToString,
            ),
            'PostPaymentResult': grpc.unary_unary_rpc_method_handler(
                    servicer.PostPaymentResult,
                    request_deserializer=seckill__pb2.PostPaymentResultRequest.FromString,
                    response_serializer=seckill__pb2.PostPaymentResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SeckillService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SeckillService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeckillService(object):
    """
    Overview: 
    1. GetSeckillDetail: GetSeckillDetailRequest -> GetSeckillDetailResponse
    2. GetSeckillList: GetSeckillListRequest -> GetSeckillListResponse
    3. GetOrderList: GetOrderListRequest -> GetOrderListResponse
    4. CreateOrder: CreateOrderRequest -> CreateOrderResponse
    5. MakePayment: MakePaymentRequest -> MakePaymentResponse
    6. PostPaymentResult: PostPaymentResultRequest -> PostPaymentResultResponse

    Services
    """

    @staticmethod
    def GetSeckillDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SeckillService/GetSeckillDetail',
            seckill__pb2.GetSeckillDetailRequest.SerializeToString,
            seckill__pb2.GetSeckillDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeckillList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SeckillService/GetSeckillList',
            seckill__pb2.GetSeckillListRequest.SerializeToString,
            seckill__pb2.GetSeckillListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SeckillService/GetOrderList',
            seckill__pb2.GetOrderListRequest.SerializeToString,
            seckill__pb2.GetOrderListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SeckillService/CreateOrder',
            seckill__pb2.CreateOrderRequest.SerializeToString,
            seckill__pb2.CreateOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SeckillService/MakePayment',
            seckill__pb2.MakePaymentRequest.SerializeToString,
            seckill__pb2.MakePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostPaymentResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SeckillService/PostPaymentResult',
            seckill__pb2.PostPaymentResultRequest.SerializeToString,
            seckill__pb2.PostPaymentResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
