# Generated by Django 6.0.4 on 2026-05-17 07:48

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(default=management.models.generate_id, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.BigIntegerField()),
                ('order_str', models.TextField()),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(default=management.models.generate_id, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('covers', models.JSONField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seckill',
            fields=[
                ('id', models.BigAutoField(default=management.models.generate_id, primary_key=True, serialize=False)),
                ('seckill_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stock', models.IntegerField()),
                ('max_per_buyer', models.IntegerField(blank=True, null=True)),
                ('version_id', models.CharField(default=management.models.generate_version_id, max_length=100)),
            ],
            options={
                'db_table': 'seckill',
                'managed': False,
            },
        ),
    ]
