"""ForeignKey kwargs edited

Revision ID: 15643c814c6c
Revises: c09cd6b1ed1b
Create Date: 2026-05-12 17:26:49.104210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15643c814c6c'
down_revision: Union[str, Sequence[str], None] = 'c09cd6b1ed1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'seckill_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('seckill', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seckill', 'product_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('order', 'seckill_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
