"""

Revision ID: 7db683b8bdd3
Revises: 15643c814c6c
Create Date: 2026-05-12 18:32:42.617459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7db683b8bdd3'
down_revision: Union[str, Sequence[str], None] = '15643c814c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.String(length=200), nullable=False))
    op.drop_column('order', 'address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('order', 'address')
    # ### end Alembic commands ###
