"""message

Revision ID: a6fe2088876b
Revises: 42179800e162
Create Date: 2026-05-13 14:05:42.465849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fe2088876b'
down_revision: Union[str, Sequence[str], None] = '42179800e162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk_user_seckill', 'order', ['user_id', 'seckill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_user_seckill', 'order', type_='unique')
    # ### end Alembic commands ###
