"""The kwargs of Order.order_str edited

Revision ID: c09cd6b1ed1b
Revises: 568fb9a08d08
Create Date: 2026-05-12 17:25:27.595741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09cd6b1ed1b'
down_revision: Union[str, Sequence[str], None] = '568fb9a08d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_str', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_str')
    # ### end Alembic commands ###
