syntax = "proto3";

/*
Overview: 
1. SendSMSCode: SendSMSCodeRequest -> Empty
2. Login: LoginRequest -> AuthInfoResponse
3. UpdateAccessToken: UpdateAccessTokenRequest -> UpdateAccessTokenResponse
*/

import "google/protobuf/empty.proto";

// Services
service AuthService {
    rpc SendSMSCode(SendSMSCodeRequest) returns (google.protobuf.Empty);
    rpc Login(LoginRequest) returns (AuthInfoResponse);
    rpc UpdateAccessToken(UpdateAccessTokenRequest) returns (UpdateAccessTokenResponse);
}

// For nesting
message UserInfo {
    uint64 id = 1;
    string tel = 2;
    string username = 3;
    string avatar = 4;
    bool is_seller = 5;
    string last_login = 7;
}

// Requests
message SendSMSCodeRequest {
    string tel = 1;
}

message LoginRequest {
    string tel = 1;
    string code = 2;
}

message UpdateAccessTokenRequest{
    string token = 1;
    uint64 user_id = 2;
}

// Responses
message AuthInfoResponse {
    UserInfo user = 1;
    string access_token = 2;
    string refresh_token = 3;
}

message UpdateAccessTokenResponse{
    string token = 1;
}
